version: '3.3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dsju
      MYSQL_DATABASE: dsju
      MYSQL_USER: dsju
      MYSQL_PASSWORD: dsju
    networks:
      - dsju
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: dsju
    networks:
      - dsju
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: dsju
      WORDPRESS_DB_PASSWORD: dsju
      WORDPRESS_DB_NAME: dsju
    networks:
      - dsju
networks:
  dsju:
volumes:
  db_data:
